-- Queries 

	-- 1	FIND THE ITEM WITH MINIMUM WEIGHT

    SELECT MIN(weight) as Weight FROM ITEMS;
    SELECT DISTINCT(DES) FROM ITEMS WHERE WEIGHT = ( SELECT MIN(weight) as Weight FROM ITEMS );
    
    -- 2 FIND THE DIFFRENT WAREHOUSES IN SPECIFIC CITY:
    
    SELECT * FROM WAREHOUSES WHERE LOCATION = 'AHMEDABAD';
	SELECT * FROM WAREHOUSES WHERE LOCATION = 'MUMBAI';
    
    -- 3 FIND A DETAILS OF ITEMS ORDERED BY A CUSTOMER:
    
    SELECT C.CNAME , I.DES , O.ONO , I.ITEMNO FROM CUSTOMER C INNER JOIN ORDERS O ON O.CNO = C.CNO
    INNER JOIN ORDERED_QUANTITY OQ ON O.ONO = OQ.ONO
    INNER JOIN ITEMS I ON OQ.ITEMNO = I.ITEMNO
    WHERE CNAME = 'AMAN';
    
  -- 4 FIND THE WAREHOUSE WHICH HAS MAXIMUM STORES

    -- (A)
    SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID;
    -- (B)
    SELECT MAX( MYCOUNT ) FROM ( SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID ) SUB ;
	-- (C)
    SELECT WID , COUNT(SID) FROM STORES GROUP BY WID HAVING COUNT(SID) = (SELECT MAX( MYCOUNT ) FROM ( SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID ) SUB );
	
    -- (ANS)
    SELECT WNAME FROM WAREHOUSES WHERE WID = (SELECT WID FROM STORES GROUP BY WID HAVING COUNT(SID) = (SELECT MAX( MYCOUNT ) FROM ( SELECT WID , COUNT(SID) MYCOUNT FROM STORES GROUP BY WID ) SUB ) );


	-- 5 FIND AN ITEM WHICH IS ORDERED FOR THE MINIMUM NUMBER OF TIME

    -- (A)
	SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO;
	-- (B)
	SELECT MIN( MYCOUNT ) FROM ( SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO )SUB; 
	-- (C)
    SELECT ITEMNO , COUNT(ONO) FROM ORDERED_QUANTITY GROUP BY ITEMNO HAVING COUNT(ONO) = (SELECT MIN( MYCOUNT ) FROM ( SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO )SUB);
	
    -- (ANS)
    SELECT DES FROM ITEMS WHERE ITEMNO = ( SELECT ITEMNO FROM ORDERED_QUANTITY GROUP BY ITEMNO HAVING COUNT(ONO) = (SELECT MIN( MYCOUNT ) FROM ( SELECT ITEMNO , COUNT(ONO) MYCOUNT FROM ORDERED_QUANTITY GROUP BY ITEMNO ) SUB) );

	-- 6	FIND TOTAL ORDERS PLACED FROM EACH CUSTOMER
    
    SELECT CNAME , COUNT(ONO) AS TOTAL_COUNT FROM CUSTOMER C INNER JOIN ORDERS O ON C.CNO = O.CNO GROUP BY C.CNAME ORDER BY TOTAL_COUNT DESC;
     